name=UBMA250
version=1.0.0
author=Cesar Bautista <cesar.bautista@uelectronics.com>, Unit Electronics, TinyCircuits <info@tiny-circuits.com>
maintainer=Unit Electronics <cotizaciones@uelectronics.com>
sentence=Arduino library for the Bosch BMA250 Accelerometer
paragraph=Allows easy reading of the sensor in all three axes of acceleration, as well as temperature in degrees Celsius
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_bma250_library
architectures=*